export const mapperTypes = {
    SET_INIT_UC_DATA: "SET_INIT_UC_DATA",
    SET_MAPPING_RESULT: "SET_MAPPING_RESULT",
    SET_MAPPING_RESULT_OBJECT: "SET_MAPPING_RESULT_OBJECT",
    DELETE_MAPPING_RESULT_OBJECT_KEY: 'DELETE_MAPPING_RESULT_OBJECT_KEY'
}