export const mapperTypes = {
    SET_INIT_UC_DATA: "SET_INIT_UC_DATA",
    SET_MAPPING_RESULT: "SET_MAPPING_RESULT",
    SET_MAPPING_RESULT_OBJECT: "SET_MAPPING_RESULT_OBJECT",
    ADD_SIGNAL_TO_MAPPING_OBJ: "ADD_SIGNAL_TO_MAPPING_OBJ"
}